/**
 * ROLE — Backend entrypoint (Express + WebSocket)
 *
 * Starts the Node server.
 * - Initializes required directories (uploads + HLS output)
 * - Serves the frontend from `public/`
 * - Mounts HTTP API + HLS routes from `routes.js`
 * - Attaches the WebSocket server on `/ws` from `websocket.js`
 */

import express from 'express';
import { createServer } from 'http';
import path from 'path';
import fs from 'fs';
import { config, log, state } from './core.js';
import routes from './routes.js';
import { createWebSocketServer } from './websocket.js';
import * as services from './services.js';

// ════════════════════════════════════════════════════════════════════════════════
// DIRECTORY INITIALIZATION
// ════════════════════════════════════════════════════════════════════════════════

/**
 * Create required directories if they don't exist
 * - media/ : User-uploaded videos
 * - public/hls/ : HLS segments generated by FFmpeg
 */
function initDirectories() {
  const dirs = [config.mediaDir, config.hlsDir];
  
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      log.info('INIT', `Directory created: ${dir}`);
    }
  }
}

// ════════════════════════════════════════════════════════════════════════════════
// EXPRESS CONFIGURATION
// ════════════════════════════════════════════════════════════════════════════════

initDirectories();

const app = express();
const server = createServer(app);

// ─── Middleware ────────────────────────────────────────────────────────────────
app.use(express.json());  // Parse JSON bodies for POST requests

// HTTP request logging (debug mode only)
app.use((req, res, next) => {
  log.debug('HTTP', `${req.method} ${req.path}`);
  next();
});

// ─── Static files ──────────────────────────────────────────────────────────────
app.use(express.static(path.join(config.baseDir, 'public'), { index: 'index.html' }));
app.use('/media', express.static(config.mediaDir));  // Uploaded videos

// ─── API routes ────────────────────────────────────────────────────────────────
app.use(routes);

// Root fallback
app.get('/', (req, res) => {
  res.sendFile(path.join(config.baseDir, 'public', 'index.html'));
});

// ════════════════════════════════════════════════════════════════════════════════
// SERVER STARTUP
// ════════════════════════════════════════════════════════════════════════════════

// Initialize WebSocket server for real-time communication
createWebSocketServer(server);

// Start listening on configured port
server.listen(config.port, () => {
  log.info('SERVER', '═══════════════════════════════════════════════════');
  log.info('SERVER', '  STC');
  log.info('SERVER', '═══════════════════════════════════════════════════');
  log.info('SERVER', `   Server started on port ${config.port}`);
  log.info('SERVER', `   Media directory: ${config.mediaDir}`);
  log.info('SERVER', `   HLS segment duration: ${config.hlsSegmentDuration}s`);
  log.info('SERVER', `   Default delay: ${state.delaySec}s`);
  log.info('SERVER', '═══════════════════════════════════════════════════');
  log.info('SERVER', '  Interfaces:');
  log.info('SERVER', `    Admin:     http://localhost:${config.port}/admin.html`);
  log.info('SERVER', `    Subtitler: http://localhost:${config.port}/subtitler.html`);
  log.info('SERVER', `    Spectator: http://localhost:${config.port}/spectator.html`);
  log.info('SERVER', '═══════════════════════════════════════════════════');
});

// ════════════════════════════════════════════════════════════════════════════════
// GRACEFUL SHUTDOWN
// ════════════════════════════════════════════════════════════════════════════════

/**
 * Handle clean server shutdown (SIGTERM, SIGINT)
 * - Stop FFmpeg streaming if active
 * - Close all connections
 * - Release resources
 */
const shutdown = async () => {
  log.info('SERVER', 'Shutting down...');
  
  // Stop streaming if active
  if (state.ffmpegProc) {
    await services.stopLive();
  }
  
  // Close HTTP server
  server.close(() => {
    log.info('SERVER', 'Server closed. Bye!');
    process.exit(0);
  });
  
  // Force exit after 5s if server does not respond
  setTimeout(() => process.exit(1), 5000);
};

// Listen for termination signals
process.on('SIGTERM', shutdown);  // Docker stop
process.on('SIGINT', shutdown);   // Ctrl+C
